output_dir: ~/code/scratch/torchprotein_output/

dataset:
  class: SubcellularLocalization
  path: ~/code/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 550
        random: True
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: ESM
    path: ~/code/scratch/esm2-model-weights/
    model: ESM-2-8M
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 1

lr_ratio: 0.1

train:
  num_epoch: 100